ground_plane_segmenter_node:
  ros__parameters:
    distance_threshold: 0.08 # Distance threshold for plane segmentation
    plane_thresh: 0.08  # Points within this distance of the estimated ground plane are considered part of the ground in meters
    eps_angle: 10.0  # Maximum angle of plane in degrees
    max_z: -0.5  # Ignore points above this height in meters
    accumulation_count: 1  # Number of frames to accumulate before plane segmentation
